# Generated by Django 3.2.7 on 2021-09-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='Sample', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='Matrix', max_length=255),
        ),
    ]
