# Generated by Django 3.2.7 on 2021-09-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library_app', '0002_auto_20210918_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='launch_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(blank=True, default='Sample description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='Matrix', max_length=255, unique=True),
        ),
    ]
