# Generated by Django 3.2.7 on 2021-09-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library_app', '0003_auto_20210919_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='launch_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
