# Generated by Django 3.2.7 on 2021-09-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library_app', '0004_alter_movie_launch_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='launch_date',
            new_name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, default='Sample description'),
        ),
    ]
