# Generated by Django 3.2.7 on 2021-09-29 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library_app', '0006_auto_20210928_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusinfo',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Other'), (1, 'Comedy'), (4, 'Action'), (2, 'Horror'), (3, 'Drama')], default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, default='')),
                ('stars', models.PositiveSmallIntegerField(default=5)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_library_app.movie')),
            ],
        ),
    ]
