# Generated by Django 3.2.7 on 2021-09-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library_app', '0007_auto_20210929_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusinfo',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Other'), (1, 'Comedy'), (3, 'Drama'), (4, 'Action'), (2, 'Horror')], default=0),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('films', models.ManyToManyField(to='movie_library_app.Movie')),
            ],
        ),
    ]
