# Generated by Django 3.2.7 on 2021-10-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library_app', '0010_alter_bonusinfo_film_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusinfo',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Comedy'), (3, 'Drama'), (4, 'Action'), (2, 'Horror'), (0, 'Other')], default=0),
        ),
    ]
