# Generated by Django 3.2.7 on 2021-10-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library_app', '0017_alter_bonusinfo_film_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusinfo',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Horror'), (4, 'Action'), (1, 'Comedy'), (3, 'Drama'), (0, 'Other')], default=0),
        ),
    ]
