# Generated by Django 3.2.7 on 2021-10-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library_app', '0021_alter_bonusinfo_film_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusinfo',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Action'), (3, 'Drama'), (2, 'Horror'), (0, 'Other'), (1, 'Comedy')], default=0),
        ),
    ]
