# Generated by Django 3.2.8 on 2021-10-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library_app', '0022_alter_bonusinfo_film_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusinfo',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Drama'), (0, 'Other'), (4, 'Action'), (2, 'Horror'), (1, 'Comedy')], default=0),
        ),
    ]
